import './components/header.js';
import './components/dropdown.js';
import './components/burger.js';
import './components/search.js';
import './components/transfer.js';
import './components/swipers.js';
import './components/mixitup.js';
import './components/counter.js';
import './components/modals.js';